package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="db_stuart_it"
)
public class Admin  implements java.io.Serializable {


     private String id;
     private String username;
     private String password;
     private String name;

    public Admin() {
    }

    public Admin(String id, String username, String password, String name) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=7)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=16)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=16)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


