package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttendanceId generated by hbm2java
 */
@Embeddable
public class AttendanceId  implements java.io.Serializable {


     private int scheduleSemester;
     private String scheduleStudentNrp;
     private String courseId;

    public AttendanceId() {
    }

    public AttendanceId(int scheduleSemester, String scheduleStudentNrp, String courseId) {
       this.scheduleSemester = scheduleSemester;
       this.scheduleStudentNrp = scheduleStudentNrp;
       this.courseId = courseId;
    }
   


    @Column(name="Schedule_semester", nullable=false)
    public int getScheduleSemester() {
        return this.scheduleSemester;
    }
    
    public void setScheduleSemester(int scheduleSemester) {
        this.scheduleSemester = scheduleSemester;
    }


    @Column(name="Schedule_Student_nrp", nullable=false, length=7)
    public String getScheduleStudentNrp() {
        return this.scheduleStudentNrp;
    }
    
    public void setScheduleStudentNrp(String scheduleStudentNrp) {
        this.scheduleStudentNrp = scheduleStudentNrp;
    }


    @Column(name="Course_id", nullable=false, length=5)
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttendanceId) ) return false;
		 AttendanceId castOther = ( AttendanceId ) other; 
         
		 return (this.getScheduleSemester()==castOther.getScheduleSemester())
 && ( (this.getScheduleStudentNrp()==castOther.getScheduleStudentNrp()) || ( this.getScheduleStudentNrp()!=null && castOther.getScheduleStudentNrp()!=null && this.getScheduleStudentNrp().equals(castOther.getScheduleStudentNrp()) ) )
 && ( (this.getCourseId()==castOther.getCourseId()) || ( this.getCourseId()!=null && castOther.getCourseId()!=null && this.getCourseId().equals(castOther.getCourseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getScheduleSemester();
         result = 37 * result + ( getScheduleStudentNrp() == null ? 0 : this.getScheduleStudentNrp().hashCode() );
         result = 37 * result + ( getCourseId() == null ? 0 : this.getCourseId().hashCode() );
         return result;
   }   


}


