package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attendance generated by hbm2java
 */
@Entity
@Table(name="attendance"
    ,catalog="db_stuart_it"
)
public class Attendance  implements java.io.Serializable {


     private AttendanceId id;
     private Course course;
     private Schedule schedule;
     private int count;

    public Attendance() {
    }

    public Attendance(AttendanceId id, Course course, Schedule schedule, int count) {
       this.id = id;
       this.course = course;
       this.schedule = schedule;
       this.count = count;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="scheduleSemester", column=@Column(name="Schedule_semester", nullable=false) ), 
        @AttributeOverride(name="scheduleStudentNrp", column=@Column(name="Schedule_Student_nrp", nullable=false, length=7) ), 
        @AttributeOverride(name="courseId", column=@Column(name="Course_id", nullable=false, length=5) ) } )
    public AttendanceId getId() {
        return this.id;
    }
    
    public void setId(AttendanceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Course_id", nullable=false, insertable=false, updatable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Schedule_semester", referencedColumnName="semester", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Schedule_Student_nrp", referencedColumnName="Student_nrp", nullable=false, insertable=false, updatable=false) } )
    public Schedule getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }

    
    @Column(name="count", nullable=false)
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }




}


