package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursecategory generated by hbm2java
 */
@Entity
@Table(name="coursecategory"
    ,catalog="db_stuart_it"
)
public class Coursecategory  implements java.io.Serializable {


     private String id;
     private String name;
     private Set<Course> courses = new HashSet<Course>(0);

    public Coursecategory() {
    }

	
    public Coursecategory(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Coursecategory(String id, String name, Set<Course> courses) {
       this.id = id;
       this.name = name;
       this.courses = courses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=5)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coursecategory")
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }




}


