package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GradeId generated by hbm2java
 */
@Embeddable
public class GradeId  implements java.io.Serializable {


     private String courseId;
     private String studentNrp;

    public GradeId() {
    }

    public GradeId(String courseId, String studentNrp) {
       this.courseId = courseId;
       this.studentNrp = studentNrp;
    }
   


    @Column(name="Course_id", nullable=false, length=5)
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }


    @Column(name="Student_nrp", nullable=false, length=7)
    public String getStudentNrp() {
        return this.studentNrp;
    }
    
    public void setStudentNrp(String studentNrp) {
        this.studentNrp = studentNrp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GradeId) ) return false;
		 GradeId castOther = ( GradeId ) other; 
         
		 return ( (this.getCourseId()==castOther.getCourseId()) || ( this.getCourseId()!=null && castOther.getCourseId()!=null && this.getCourseId().equals(castOther.getCourseId()) ) )
 && ( (this.getStudentNrp()==castOther.getStudentNrp()) || ( this.getStudentNrp()!=null && castOther.getStudentNrp()!=null && this.getStudentNrp().equals(castOther.getStudentNrp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCourseId() == null ? 0 : this.getCourseId().hashCode() );
         result = 37 * result + ( getStudentNrp() == null ? 0 : this.getStudentNrp().hashCode() );
         return result;
   }   


}


