package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name="grade"
    ,catalog="db_stuart_it"
)
public class Grade  implements java.io.Serializable {


     private GradeId id;
     private Course course;
     private Student student;
     private Double utsGrade;
     private Double uasGrade;
     private Double katGrade;
     private String gradecol;
     private Character gradeLetter;

    public Grade() {
    }

	
    public Grade(GradeId id, Course course, Student student) {
        this.id = id;
        this.course = course;
        this.student = student;
    }
    public Grade(GradeId id, Course course, Student student, Double utsGrade, Double uasGrade, Double katGrade, String gradecol, Character gradeLetter) {
       this.id = id;
       this.course = course;
       this.student = student;
       this.utsGrade = utsGrade;
       this.uasGrade = uasGrade;
       this.katGrade = katGrade;
       this.gradecol = gradecol;
       this.gradeLetter = gradeLetter;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="courseId", column=@Column(name="Course_id", nullable=false, length=5) ), 
        @AttributeOverride(name="studentNrp", column=@Column(name="Student_nrp", nullable=false, length=7) ) } )
    public GradeId getId() {
        return this.id;
    }
    
    public void setId(GradeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Course_id", nullable=false, insertable=false, updatable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Student_nrp", nullable=false, insertable=false, updatable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="uts_grade", precision=22, scale=0)
    public Double getUtsGrade() {
        return this.utsGrade;
    }
    
    public void setUtsGrade(Double utsGrade) {
        this.utsGrade = utsGrade;
    }

    
    @Column(name="uas_grade", precision=22, scale=0)
    public Double getUasGrade() {
        return this.uasGrade;
    }
    
    public void setUasGrade(Double uasGrade) {
        this.uasGrade = uasGrade;
    }

    
    @Column(name="kat_grade", precision=22, scale=0)
    public Double getKatGrade() {
        return this.katGrade;
    }
    
    public void setKatGrade(Double katGrade) {
        this.katGrade = katGrade;
    }

    
    @Column(name="Gradecol", length=45)
    public String getGradecol() {
        return this.gradecol;
    }
    
    public void setGradecol(String gradecol) {
        this.gradecol = gradecol;
    }

    
    @Column(name="grade_letter", length=1)
    public Character getGradeLetter() {
        return this.gradeLetter;
    }
    
    public void setGradeLetter(Character gradeLetter) {
        this.gradeLetter = gradeLetter;
    }




}


