package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name="log"
    ,catalog="db_stuart_it"
)
public class Log  implements java.io.Serializable {


     private String logid;
     private String activityName;
     private String content;

    public Log() {
    }

    public Log(String logid, String activityName, String content) {
       this.logid = logid;
       this.activityName = activityName;
       this.content = content;
    }
   
     @Id 

    
    @Column(name="logid", unique=true, nullable=false, length=12)
    public String getLogid() {
        return this.logid;
    }
    
    public void setLogid(String logid) {
        this.logid = logid;
    }

    
    @Column(name="activity_name", nullable=false, length=10)
    public String getActivityName() {
        return this.activityName;
    }
    
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    
    @Column(name="content", nullable=false, length=200)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


