package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name="report"
    ,catalog="db_stuart_it"
    , uniqueConstraints = @UniqueConstraint(columnNames="id") 
)
public class Report  implements java.io.Serializable {


     private ReportId id;
     private Student student;
     private String message;

    public Report() {
    }

    public Report(ReportId id, Student student, String message) {
       this.id = id;
       this.student = student;
       this.message = message;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", unique=true, nullable=false, length=45) ), 
        @AttributeOverride(name="studentNrp", column=@Column(name="Student_nrp", nullable=false, length=7) ) } )
    public ReportId getId() {
        return this.id;
    }
    
    public void setId(ReportId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Student_nrp", nullable=false, insertable=false, updatable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="message", nullable=false, length=500)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


