package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReportId generated by hbm2java
 */
@Embeddable
public class ReportId  implements java.io.Serializable {


     private String id;
     private String studentNrp;

    public ReportId() {
    }

    public ReportId(String id, String studentNrp) {
       this.id = id;
       this.studentNrp = studentNrp;
    }
   


    @Column(name="id", unique=true, nullable=false, length=45)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }


    @Column(name="Student_nrp", nullable=false, length=7)
    public String getStudentNrp() {
        return this.studentNrp;
    }
    
    public void setStudentNrp(String studentNrp) {
        this.studentNrp = studentNrp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReportId) ) return false;
		 ReportId castOther = ( ReportId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getStudentNrp()==castOther.getStudentNrp()) || ( this.getStudentNrp()!=null && castOther.getStudentNrp()!=null && this.getStudentNrp().equals(castOther.getStudentNrp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getStudentNrp() == null ? 0 : this.getStudentNrp().hashCode() );
         return result;
   }   


}


