package com.stuart.entity;
// Generated Oct 13, 2019 7:46:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="db_stuart_it"
)
public class Student  implements java.io.Serializable {


     private String nrp;
     private String username;
     private String password;
     private String ipkTotal;
     private String firstName;
     private String lastName;
     private Set<Grade> grades = new HashSet<Grade>(0);
     private Set<Report> reports = new HashSet<Report>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public Student() {
    }

	
    public Student(String nrp, String username, String password, String ipkTotal, String firstName) {
        this.nrp = nrp;
        this.username = username;
        this.password = password;
        this.ipkTotal = ipkTotal;
        this.firstName = firstName;
    }
    public Student(String nrp, String username, String password, String ipkTotal, String firstName, String lastName, Set<Grade> grades, Set<Report> reports, Set<Schedule> schedules) {
       this.nrp = nrp;
       this.username = username;
       this.password = password;
       this.ipkTotal = ipkTotal;
       this.firstName = firstName;
       this.lastName = lastName;
       this.grades = grades;
       this.reports = reports;
       this.schedules = schedules;
    }
   
     @Id 

    
    @Column(name="nrp", unique=true, nullable=false, length=7)
    public String getNrp() {
        return this.nrp;
    }
    
    public void setNrp(String nrp) {
        this.nrp = nrp;
    }

    
    @Column(name="username", nullable=false, length=16)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=16)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="ipk_total", nullable=false, length=45)
    public String getIpkTotal() {
        return this.ipkTotal;
    }
    
    public void setIpkTotal(String ipkTotal) {
        this.ipkTotal = ipkTotal;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<Grade> getGrades() {
        return this.grades;
    }
    
    public void setGrades(Set<Grade> grades) {
        this.grades = grades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<Report> getReports() {
        return this.reports;
    }
    
    public void setReports(Set<Report> reports) {
        this.reports = reports;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }




}


